export const WORST_ADVICE_PROMPTS = [
  "Your date is 20 minutes late",
  "You just got pulled over for speeding",
  "Your boss catches you napping at your desk",
  "You accidentally liked your ex's photo from 3 years ago",
  "You're stuck in an elevator with your crush",
  "Your friend asks you to help them move... again",
  "You just sent a text to the wrong person",
  "Your card gets declined on a first date",
  "You realize you've been on mute for 10 minutes",
  "Your neighbor's dog won't stop barking at 3am",
  "You accidentally call your teacher 'mom'",
  "You show up to a costume party and no one else is in costume",
  "Your phone dies during an important call",
  "You walk into a glass door in front of everyone",
  "Your fly has been down all day and no one told you",
  "You accidentally reply-all with something embarrassing",
  "Your stomach growls during a moment of silence",
  "You get caught talking to yourself in public",
  "You wave back at someone who wasn't waving at you",
  "You realize you've been telling the same story twice",
];

export const SPEED_SUPERLATIVE_PROMPTS = [
  "Most likely to adopt a raccoon",
  "Most likely to survive a zombie apocalypse",
  "Most likely to accidentally start a cult",
  "Most likely to get arrested for something stupid",
  "Most likely to cry during a commercial",
  "Most likely to eat something off the floor",
  "Most likely to become a reality TV star",
  "Most likely to forget their own birthday",
  "Most likely to fight a goose and lose",
  "Most likely to accidentally become famous",
  "Most likely to sleep through an earthquake",
  "Most likely to befriend a stranger's dog and forget the stranger",
  "Most likely to laugh at the worst possible moment",
  "Most likely to get stuck in a baby swing at the park",
  "Most likely to accidentally commit a crime",
  "Most likely to start a food fight at a fancy restaurant",
  "Most likely to get lost in their own neighborhood",
  "Most likely to text something weird to their boss",
  "Most likely to fall asleep standing up",
  "Most likely to win a hot dog eating contest",
  "Most likely to talk their way out of a speeding ticket",
  "Most likely to adopt 7 cats and name them all Greg",
  "Most likely to challenge a stranger to an arm wrestle",
  "Most likely to get banned from a buffet",
];

export const EMOJI_STORY_SEQUENCES = [
  ["\u{1F431}", "\u{1F525}", "\u{1F692}", "\u{1F631}"],
  ["\u{1F476}", "\u{1F382}", "\u{1F480}", "\u{1F47B}"],
  ["\u{1F9B7}", "\u{1F9DA}", "\u{1F4B0}", "\u{1F3C3}"],
  ["\u{1F40D}", "\u2708\uFE0F", "\u{1F628}", "\u{1FA82}"],
  ["\u{1F355}", "\u{1F4DE}", "\u{1F6AA}", "\u{1F47D}"],
  ["\u{1F415}", "\u{1F4DD}", "\u{1F393}", "\u{1F454}"],
  ["\u{1F9CA}", "\u2600\uFE0F", "\u{1F3D6}\uFE0F", "\u{1F988}"],
  ["\u{1F470}", "\u{1F3C3}", "\u{1F697}", "\u{1F32E}"],
  ["\u{1F916}", "\u2764\uFE0F", "\u{1F9F9}", "\u{1F622}"],
  ["\u{1F986}", "\u{1F451}", "\u2694\uFE0F", "\u{1F3F0}"],
  ["\u{1F9EA}", "\u{1F4A5}", "\u{1F9B8}", "\u{1F9B9}"],
  ["\u{1F438}", "\u{1F48B}", "\u{1F478}", "\u{1F922}"],
  ["\u{1F383}", "\u{1F52A}", "\u{1F631}", "\u{1F3AA}"],
  ["\u{1F412}", "\u{1F34C}", "\u{1F680}", "\u{1F319}"],
  ["\u{1F9D3}", "\u{1F48A}", "\u{1F4AA}", "\u{1F3CB}\uFE0F"],
  ["\u{1F3B8}", "\u{1F404}", "\u{1F319}", "\u{1F47D}"],
];

export const TWO_WORD_STORY_TEMPLATES = [
  "The wedding was perfect until someone brought a _____ and the priest said '_____'.",
  "My first day at work, the boss handed me a _____ and whispered '_____'.",
  "The detective found _____ in the fridge next to a note that said '_____'.",
  "At 3am, the doorbell rang. It was a _____ delivering '_____'.",
  "The fortune cookie said: 'Beware the _____ that _____.'",
  "My tinder date showed up with _____ and immediately _____.",
  "The president's speech was interrupted by _____ yelling '_____'.",
  "Grandma's secret recipe calls for _____ and a tablespoon of _____.",
  "The escape room's final clue was a _____ labeled '_____'.",
  "The last thing the astronaut saw was _____ floating past the _____.",
  "My cat brought home a _____ and dropped it on my _____.",
  "The school mascot quit after someone _____ their _____.",
  "The therapy session ended when the therapist _____ the _____.",
  "The airplane announcement said: 'Please fasten your _____ and prepare for _____.'",
  "The museum's most valuable artifact is a _____ once owned by _____.",
  "My autobiography will be titled: 'The _____ That _____.'",
];

export const BLUFF_STATS = [
  { stat: "The average person swallows 8 spiders in their sleep per year", real: false },
  { stat: "Honey never spoils \u2014 3000 year old honey is still edible", real: true },
  { stat: "A group of flamingos is called a 'flamboyance'", real: true },
  { stat: "The inventor of the Pringles can is buried in one", real: true },
  { stat: "Cows have best friends and get stressed when separated", real: true },
  { stat: "The average cloud weighs about 1.1 million pounds", real: true },
  { stat: "Bananas are technically berries, but strawberries aren't", real: true },
  { stat: "A jiffy is an actual unit of time (1/100th of a second)", real: true },
  { stat: "95% of people text things they could never say in person", real: false },
  { stat: "The moon has moonquakes", real: true },
  { stat: "Octopuses have 3 hearts and blue blood", real: true },
  { stat: "The human nose can detect over 1 trillion scents", real: true },
  { stat: "Oxford University is older than the Aztec Empire", real: true },
  { stat: "Sharks are older than trees", real: true },
  { stat: "The average person walks past 36 murderers in their lifetime", real: false },
  { stat: "Cleopatra lived closer to the Moon landing than to the building of the Great Pyramid", real: true },
  { stat: "A cockroach can live for 2 weeks without its head", real: true },
  { stat: "Nintendo was founded in 1889", real: true },
  { stat: "There are more fake flamingos in the world than real ones", real: true },
  { stat: "Humans share 60% of their DNA with bananas", real: true },
  { stat: "The average person will spend 6 months of their life waiting for red lights", real: true },
  { stat: "Vikings used to give kittens to new brides as wedding gifts", real: true },
  { stat: "Scotland's national animal is the unicorn", real: true },
  { stat: "There are more public libraries than McDonald's in the US", real: true },
];

export const ASSUMPTION_ARENA_PROMPTS = [
  "The best time to eat pizza is ___",
  "The worst superpower would be ___",
  "The most overrated movie of all time is ___",
  "If animals could talk, the rudest would be ___",
  "The most useless invention ever is ___",
  "The worst flavor of ice cream would be ___",
  "The most embarrassing thing to Google is ___",
  "If you could ban one word, it would be ___",
  "The worst place to propose is ___",
  "The most annoying sound in the world is ___",
  "The worst thing to say on a first date is ___",
  "If aliens visited Earth, the first thing they'd notice is ___",
  "The most overrated holiday is ___",
  "The worst middle name would be ___",
  "The most suspicious thing to buy at 3am is ___",
  "The worst possible Wi-Fi password is ___",
  "The most awkward text to accidentally send your boss is ___",
  "The worst theme for a birthday party is ___",
  "If life had a loading screen, the tip would be ___",
  "The most dangerous food to eat while driving is ___",
];
